class Player {
    alwaysSelectable = 0;
    labels = "Player";
    values[] = {"Ghost", "Som", "MadHatter", "Sythe", "Prophet", "Cheezy", "Foley", "Mobius", "Ratler", "Edge", "Smaug", "Taun", "Canada", "Dilanza", "Mute"};
    class Ghost { label = "Ghost"; description = "Ghost`s"; };
    class Som { label = "Som"; description = "Som`s"; };
    class MadHatter { label = "Mad Hatter"; description = "Mad Hatter`s"; };
    class Sythe { label = "Sythe"; description = "Sythe`s"; };
    class Prophet { label = "Prophet"; description = "Prophet`s"; };
    class Cheezy { label = "Cheezy"; description = "Cheezy`s"; };
    class Foley { label = "Foley"; description = "Foley`s"; };
    class Mobius { label = "Mobius"; description = "Mobius`s"; };
    class Ratler { label = "Ratler"; description = "Ratler`s"; };
    class Edge { label = "Edge"; description = "Edge`s"; };
    class Smaug { label = "Smaug"; description = "Smaug`s"; };
    class Taun { label = "Taun"; description = "Taun`s"; };
    class Canada { label = "Canada"; description = "Canada`s"; };
    class Dilanza { label = "Dilanza"; description = "Dilanza`s"; };
    class Mute { label = "Mute"; description = "Mute`s"; };
};