class Player {
    alwaysSelectable = 0;
    labels = "Player";
    values[] = {"Biedronka", "Havoc", "Hazard", "Neary", "Taylor", "Third", "Osprey", "King", "Neron", "Gecko", "Jinter", "Smokery", "Outcast", "Skylight", "Delta", "York"};
    class Biedronka { label = "Biedronka"; description = "Biedronka"; };
    class Havoc { label = "Havoc"; description = "Havoc`s"; };
    class Hazard { label = "Hazard"; description = "Hazard`s"; };
    class Neary { label = "Neary"; description = "Neary`s"; };
    class Taylor { label = "Taylor"; description = "Taylor`s"; };
    class Third { label = "Third"; description = "Third`s"; };
    class Osprey { label = "Osprey"; description = "Osprey`s"; };
    class King { label = "King"; description = "King`s Helmet"; };
    class Neron { label = "Neron"; description = "Neron`s"; };
    class Gecko { label = "Gecko"; description = "Gecko`s"; };
    class Jinter { label = "Jinter"; description = "Jinter`s"; };
    class Smokery { label = "Smokery"; description = "Smokery`s"; };
    class Outcast { label = "Outcast"; description = "Outcast`s"; };
    class Skylight { label = "Skylight"; description = "Skylight`s"; };
    class Delta { label = "Delta"; description = "Delta`s"; };
    class York { label = "York"; description = "York`s"; };
};