class ViewOptics;
class SensorTemplatePassiveRadar;
class SensorTemplateAntiRadiation;
class SensorTemplateActiveRadar;
class SensorTemplateIR;
class SensorTemplateVisual;
class SensorTemplateMan;
class SensorTemplateLaser;
class SensorTemplateNV;
class SensorTemplateDataLink;
class Optics_Armored;
class Optics_Gunner_APC_01: Optics_Armored { class Wide; class Medium; class Narrow; };
class DefaultVehicleSystemsDisplayManagerLeft { class components; };
class DefaultVehicleSystemsDisplayManagerRight { class components; };
class VehicleSystemsTemplateLeftDriver: DefaultVehicleSystemsDisplayManagerLeft { class components; };
class VehicleSystemsTemplateRightDriver: DefaultVehicleSystemsDisplayManagerRight { class components; };
class VehicleSystemsTemplateLeftCommander: DefaultVehicleSystemsDisplayManagerLeft { class components; };
class VehicleSystemsTemplateRightCommander: DefaultVehicleSystemsDisplayManagerRight { class components; };
class VehicleSystemsTemplateLeftGunner: DefaultVehicleSystemsDisplayManagerLeft { class components; };
class VehicleSystemsTemplateRightGunner: DefaultVehicleSystemsDisplayManagerRight { class components; };
class GunParticles;
class DefaultEventHandlers;
class WeaponFireGun;
class WeaponCloudsGun;
class WeaponFireMGun;
class WeaponCloudsMGun;
class RCWSOptics;