#define NEW_SHARED_LAAT_C_CONFIG() scope=2;\
		tas_can_impulse=0;\
		ls_hasImpulse = 1;\
		ls_impulsor_boostSpeed_1 = 400;\
		ls_impulsor_boostSpeed_2 = 800;\
		scopecurator=2;\
		author=QUOTE(95th Aux Team);\
		faction=QUOTE(AUX_95th_Legion_Faction_Vehicles);\
		editorSubcategory=QUOTE(AUX_95th_Legion_Vehicles_Category_Air_Gunships);\
		ace_cargo_space = 26;\
		ace_cargo_hasCargo = 1;\
        crew = QUOTE(AUX_95th_Unit_P1_Basic_Trooper);