class AUX_95th_Grappler_Ammo: B_65x39_Caseless {
	author = "95th Aux Team";
	simulation = "shotShell";
	model = "\A3\weapons_f\ammo\UGL_slug";
	suppressionRadiusHit = 0;
	timeToLive = 10;
	typicalSpeed = 22;
	aiAmmoUsageFlags = "0";
	dangerRadiusHit = 0;
	deflecting = 0;
	explosionTime = -1;
	explosive = 0;
	cost = 40;
	hit = 0;
	indirectHit = 0;
	maxSpeed = 100;
	// flaresize = 5;
	// tracerscale = 0.8;
	// effectflare = "FlareShell";
	tracerstarttime = 0.05;
	tracerendtime = 10;
	nvgonly = 0;
	airlock = 1;
	irtarget = 1;
	brightness = 1000;
	initTime = 0;
	airfriction = 0;
	coefgravity = 0;

	// soundFly[] = {"x\advanced_grappling\addons\main\sounds\launch.ogg", 3, 1, 100};
	// soundHit1[] = {"x\advanced_grappling\addons\main\sounds\impact.ogg", 3, 1, 100};
	// multiSoundHit[] = {"soundHit1", 1};
};